name: ci

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
    - cron: '00 01 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Check formatting
        run: cargo make fmt_check

      - name: Test
        run: cargo make test -- --chrome --headless
